name: "Upptime Updates"
description: "Workflow to update Upptime projects"
author: "Anand Chowdhary <https://github.com/AnandChowdhary>"
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: "umbrella"
  color: "green"
